controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix:
        fr: '/fr'
        en: '/en'
        de: '/de'
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'

home_fallback:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
    defaults:
        path: /en
        permanent: true

kernel:
    resource: ../../src/Kernel.php
    type: annotation
